# hid_report_codes.py

# Standard USB HID Keyboard Report Usage IDs
# https://www.usb.org/sites/default/files/documents/hid1_11.pdf (Page 53)
# https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf (Page 60-65)

# Modifier keys (8 bits)
MODIFIER_LEFT_CTRL = 0x01
MODIFIER_LEFT_SHIFT = 0x02
MODIFIER_LEFT_ALT = 0x04
MODIFIER_LEFT_GUI = 0x08  # Windows key, Command key
MODIFIER_RIGHT_CTRL = 0x10
MODIFIER_RIGHT_SHIFT = 0x20
MODIFIER_RIGHT_ALT = 0x40
MODIFIER_RIGHT_GUI = 0x80

MODIFIER_MAP = {
    "LEFT_CTRL": MODIFIER_LEFT_CTRL,
    "LCTRL": MODIFIER_LEFT_CTRL,
    "LEFT_SHIFT": MODIFIER_LEFT_SHIFT,
    "LSHIFT": MODIFIER_LEFT_SHIFT,
    "LEFT_ALT": MODIFIER_LEFT_ALT,
    "LALT": MODIFIER_LEFT_ALT,
    "LEFT_GUI": MODIFIER_LEFT_GUI,
    "LGUI": MODIFIER_LEFT_GUI,
    "LEFT_META": MODIFIER_LEFT_GUI, # Common alias for GUI
    "LMETA": MODIFIER_LEFT_GUI,
    "RIGHT_CTRL": MODIFIER_RIGHT_CTRL,
    "RCTRL": MODIFIER_RIGHT_CTRL,
    "RIGHT_SHIFT": MODIFIER_RIGHT_SHIFT,
    "RSHIFT": MODIFIER_RIGHT_SHIFT,
    "RIGHT_ALT": MODIFIER_RIGHT_ALT,
    "RALT": MODIFIER_RIGHT_ALT,
    "RIGHT_GUI": MODIFIER_RIGHT_GUI,
    "RGUI": MODIFIER_RIGHT_GUI,
    "RIGHT_META": MODIFIER_RIGHT_GUI,
    "RMETA": MODIFIER_RIGHT_GUI,
}

# Regular keys (up to 6 key codes)
KEY_NONE = 0x00
KEY_ERROR_ROLLOVER = 0x01
KEY_POST_FAIL = 0x02
KEY_ERROR_UNDEFINED = 0x03

KEY_A = 0x04
KEY_B = 0x05
KEY_C = 0x06
KEY_D = 0x07
KEY_E = 0x08
KEY_F = 0x09
KEY_G = 0x0A
KEY_H = 0x0B
KEY_I = 0x0C
KEY_J = 0x0D
KEY_K = 0x0E
KEY_L = 0x0F
KEY_M = 0x10
KEY_N = 0x11
KEY_O = 0x12
KEY_P = 0x13
KEY_Q = 0x14
KEY_R = 0x15
KEY_S = 0x16
KEY_T = 0x17
KEY_U = 0x18
KEY_V = 0x19
KEY_W = 0x1A
KEY_X = 0x1B
KEY_Y = 0x1C
KEY_Z = 0x1D

KEY_1 = 0x1E
KEY_2 = 0x1F
KEY_3 = 0x20
KEY_4 = 0x21
KEY_5 = 0x22
KEY_6 = 0x23
KEY_7 = 0x24
KEY_8 = 0x25
KEY_9 = 0x26
KEY_0 = 0x27

KEY_ENTER = 0x28
KEY_ESCAPE = 0x29
KEY_BACKSPACE = 0x2A
KEY_TAB = 0x2B
KEY_SPACE = 0x2C
KEY_MINUS = 0x2D
KEY_EQUAL = 0x2E
KEY_LEFTBRACE = 0x2F
KEY_RIGHTBRACE = 0x30
KEY_BACKSLASH = 0x31
KEY_NONUS_HASH = 0x32
KEY_SEMICOLON = 0x33
KEY_APOSTROPHE = 0x34
KEY_GRAVE = 0x35
KEY_COMMA = 0x36
KEY_DOT = 0x37
KEY_SLASH = 0x38
KEY_CAPSLOCK = 0x39

KEY_F1 = 0x3A
KEY_F2 = 0x3B
KEY_F3 = 0x3C
KEY_F4 = 0x3D
KEY_F5 = 0x3E
KEY_F6 = 0x3F
KEY_F7 = 0x40
KEY_F8 = 0x41
KEY_F9 = 0x42
KEY_F10 = 0x43
KEY_F11 = 0x44
KEY_F12 = 0x45

KEY_PRINTSCREEN = 0x46
KEY_SCROLLLOCK = 0x47
KEY_PAUSE = 0x48
KEY_INSERT = 0x49
KEY_HOME = 0x4A
KEY_PAGEUP = 0x4B
KEY_DELETE = 0x4C
KEY_END = 0x4D
KEY_PAGEDOWN = 0x4E
KEY_RIGHT = 0x4F
KEY_LEFT = 0x50
KEY_DOWN = 0x51
KEY_UP = 0x52
KEY_NUMLOCK = 0x53

KEY_KP_SLASH = 0x54
KEY_KP_ASTERISK = 0x55
KEY_KP_MINUS = 0x56
KEY_KP_PLUS = 0x57
KEY_KP_ENTER = 0x58
KEY_KP_1 = 0x59
KEY_KP_2 = 0x5A
KEY_KP_3 = 0x5B
KEY_KP_4 = 0x5C
KEY_KP_5 = 0x5D
KEY_KP_6 = 0x5E
KEY_KP_7 = 0x5F
KEY_KP_8 = 0x60
KEY_KP_9 = 0x61
KEY_KP_0 = 0x62
KEY_KP_DOT = 0x63

KEY_NONUS_BACKSLASH = 0x64
KEY_APPLICATION = 0x65 # Context Menu key
KEY_POWER = 0x66
KEY_KP_EQUAL = 0x67
KEY_F13 = 0x68
KEY_F14 = 0x69
KEY_F15 = 0x6A
KEY_F16 = 0x6B
KEY_F17 = 0x6C
KEY_F18 = 0x6D
KEY_F19 = 0x6E
KEY_F20 = 0x6F
KEY_F21 = 0x70
KEY_F22 = 0x71
KEY_F23 = 0x72
KEY_F24 = 0x73

KEY_MAP = {
    "NONE": KEY_NONE,
    "A": KEY_A, "B": KEY_B, "C": KEY_C, "D": KEY_D, "E": KEY_E, "F": KEY_F,
    "G": KEY_G, "H": KEY_H, "I": KEY_I, "J": KEY_J, "K": KEY_K, "L": KEY_L,
    "M": KEY_M, "N": KEY_N, "O": KEY_O, "P": KEY_P, "Q": KEY_Q, "R": KEY_R,
    "S": KEY_S, "T": KEY_T, "U": KEY_U, "V": KEY_V, "W": KEY_W, "X": KEY_X,
    "Y": KEY_Y, "Z": KEY_Z,
    "1": KEY_1, "2": KEY_2, "3": KEY_3, "4": KEY_4, "5": KEY_5,
    "6": KEY_6, "7": KEY_7, "8": KEY_8, "9": KEY_9, "0": KEY_0,
    "ENTER": KEY_ENTER, "RETURN": KEY_ENTER, "ESCAPE": KEY_ESCAPE,
    "BACKSPACE": KEY_BACKSPACE, "TAB": KEY_TAB, "SPACE": KEY_SPACE,
    "MINUS": KEY_MINUS, "EQUALS": KEY_EQUAL, "LEFTBRACE": KEY_LEFTBRACE,
    "RIGHTBRACE": KEY_RIGHTBRACE, "BACKSLASH": KEY_BACKSLASH,
    "NONUS_HASH": KEY_NONUS_HASH, "SEMICOLON": KEY_SEMICOLON,
    "APOSTROPHE": KEY_APOSTROPHE, "GRAVE": KEY_GRAVE, "TILDE": KEY_GRAVE,
    "COMMA": KEY_COMMA, "DOT": KEY_DOT, "SLASH": KEY_SLASH,
    "CAPSLOCK": KEY_CAPSLOCK,
    "F1": KEY_F1, "F2": KEY_F2, "F3": KEY_F3, "F4": KEY_F4, "F5": KEY_F5,
    "F6": KEY_F6, "F7": KEY_F7, "F8": KEY_F8, "F9": KEY_F9, "F10": KEY_F10,
    "F11": KEY_F11, "F12": KEY_F12,
    "PRINTSCREEN": KEY_PRINTSCREEN, "SCROLLLOCK": KEY_SCROLLLOCK,
    "PAUSE": KEY_PAUSE, "INSERT": KEY_INSERT, "HOME": KEY_HOME,
    "PAGEUP": KEY_PAGEUP, "DELETE": KEY_DELETE, "END": KEY_END,
    "PAGEDOWN": KEY_PAGEDOWN,
    "RIGHT": KEY_RIGHT, "LEFT": KEY_LEFT, "DOWN": KEY_DOWN, "UP": KEY_UP,
    "NUMLOCK": KEY_NUMLOCK,
    "KP_SLASH": KEY_KP_SLASH, "KP_ASTERISK": KEY_KP_ASTERISK,
    "KP_MINUS": KEY_KP_MINUS, "KP_PLUS": KEY_KP_PLUS,
    "KP_ENTER": KEY_KP_ENTER,
    "KP_1": KEY_KP_1, "KP_2": KEY_KP_2, "KP_3": KEY_KP_3, "KP_4": KEY_KP_4,
    "KP_5": KEY_KP_5, "KP_6": KEY_KP_6, "KP_7": KEY_KP_7, "KP_8": KEY_KP_8,
    "KP_9": KEY_KP_9, "KP_0": KEY_KP_0, "KP_DOT": KEY_KP_DOT,
    "NONUS_BACKSLASH": KEY_NONUS_BACKSLASH,
    "APPLICATION": KEY_APPLICATION, # Context Menu key
    "POWER": KEY_POWER,
    "KP_EQUAL": KEY_KP_EQUAL,
    "F13": KEY_F13, "F14": KEY_F14, "F15": KEY_F15, "F16": KEY_F16,
    "F17": KEY_F17, "F18": KEY_F18, "F19": KEY_F19, "F20": KEY_F20,
    "F21": KEY_F21, "F22": KEY_F22, "F23": KEY_F23, "F24": KEY_F24,
}

# Mouse buttons (first byte of mouse report)
MOUSE_BUTTON_LEFT = 0x01
MOUSE_BUTTON_RIGHT = 0x02
MOUSE_BUTTON_MIDDLE = 0x04

MOUSE_BUTTON_MAP = {
    "LEFT": MOUSE_BUTTON_LEFT,
    "RIGHT": MOUSE_BUTTON_RIGHT,
    "MIDDLE": MOUSE_BUTTON_MIDDLE,
}

# ASCII to HID Keycode mapping for basic characters
# This handles only unshifted characters. Shifted characters require modifier.
ASCII_TO_HID = {
    'a': KEY_A, 'b': KEY_B, 'c': KEY_C, 'd': KEY_D, 'e': KEY_E, 'f': KEY_F,
    'g': KEY_G, 'h': KEY_H, 'i': KEY_I, 'j': KEY_J, 'k': KEY_K, 'l': KEY_L,
    'm': KEY_M, 'n': KEY_N, 'o': KEY_O, 'p': KEY_P, 'q': KEY_Q, 'r': KEY_R,
    's': KEY_S, 't': KEY_T, 'u': KEY_U, 'v': KEY_V, 'w': KEY_W, 'x': KEY_X,
    'y': KEY_Y, 'z': KEY_Z,
    'A': (KEY_A, MODIFIER_LEFT_SHIFT), 'B': (KEY_B, MODIFIER_LEFT_SHIFT), 'C': (KEY_C, MODIFIER_LEFT_SHIFT),
    'D': (KEY_D, MODIFIER_LEFT_SHIFT), 'E': (KEY_E, MODIFIER_LEFT_SHIFT), 'F': (KEY_F, MODIFIER_LEFT_SHIFT),
    'G': (KEY_G, MODIFIER_LEFT_SHIFT), 'H': (KEY_H, MODIFIER_LEFT_SHIFT), 'I': (KEY_I, MODIFIER_LEFT_SHIFT),
    'J': (KEY_J, MODIFIER_LEFT_SHIFT), 'K': (KEY_K, MODIFIER_LEFT_SHIFT), 'L': (KEY_L, MODIFIER_LEFT_SHIFT),
    'M': (KEY_M, MODIFIER_LEFT_SHIFT), 'N': (KEY_N, MODIFIER_LEFT_SHIFT), 'O': (KEY_O, MODIFIER_LEFT_SHIFT),
    'P': (KEY_P, MODIFIER_LEFT_SHIFT), 'Q': (KEY_Q, MODIFIER_LEFT_SHIFT), 'R': (KEY_R, MODIFIER_LEFT_SHIFT),
    'S': (KEY_S, MODIFIER_LEFT_SHIFT), 'T': (KEY_T, MODIFIER_LEFT_SHIFT), 'U': (KEY_U, MODIFIER_LEFT_SHIFT),
    'V': (KEY_V, MODIFIER_LEFT_SHIFT), 'W': (KEY_W, MODIFIER_LEFT_SHIFT), 'X': (KEY_X, MODIFIER_LEFT_SHIFT),
    'Y': (KEY_Y, MODIFIER_LEFT_SHIFT), 'Z': (KEY_Z, MODIFIER_LEFT_SHIFT),

    '1': KEY_1, '2': KEY_2, '3': KEY_3, '4': KEY_4, '5': KEY_5,
    '6': KEY_6, '7': KEY_7, '8': KEY_8, '9': KEY_9, '0': KEY_0,

    '!': (KEY_1, MODIFIER_LEFT_SHIFT), '@': (KEY_2, MODIFIER_LEFT_SHIFT), '#': (KEY_3, MODIFIER_LEFT_SHIFT),
    '$': (KEY_4, MODIFIER_LEFT_SHIFT), '%': (KEY_5, MODIFIER_LEFT_SHIFT), '^': (KEY_6, MODIFIER_LEFT_SHIFT),
    '&': (KEY_7, MODIFIER_LEFT_SHIFT), '*': (KEY_8, MODIFIER_LEFT_SHIFT), '(': (KEY_9, MODIFIER_LEFT_SHIFT),
    ')': (KEY_0, MODIFIER_LEFT_SHIFT),

    '-': KEY_MINUS, '_': (KEY_MINUS, MODIFIER_LEFT_SHIFT),
    '=': KEY_EQUAL, '+': (KEY_EQUAL, MODIFIER_LEFT_SHIFT),
    '[': KEY_LEFTBRACE, '{': (KEY_LEFTBRACE, MODIFIER_LEFT_SHIFT),
    ']': KEY_RIGHTBRACE, '}': (KEY_RIGHTBRACE, MODIFIER_LEFT_SHIFT),
    '\\': KEY_BACKSLASH, '|': (KEY_BACKSLASH, MODIFIER_LEFT_SHIFT),
    ';': KEY_SEMICOLON, ':': (KEY_SEMICOLON, MODIFIER_LEFT_SHIFT),
    "'": KEY_APOSTROPHE, '"': (KEY_APOSTROPHE, MODIFIER_LEFT_SHIFT),
}